# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200624_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='category',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
